# Header
menu:
  Home: /
  Archives: /archives
  About Me: /about
  Licenses: /licenses
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
ggoogle_analytics: 51163188
favicon: /images/favicon.png
twitter: 582517077
google_plus: 108532519435736921327
fb_admins:
fb_app_id:
